# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-benchmark
  namespace: vault-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-benchmark-configmap
  namespace: vault-ns
data:
  k8s.hcl: |
    # Basic Benchmark config options
    vault_addr = "https://vault-private-vault-959f2c14.23069dd1.z1.hashicorp.cloud:8200"
    vault_token = "hvs.CAESIBUDQQFmKmBV5kzwMDoVCSFHL5SF-bh57jrimubS8PFEGigKImh2cy5BNjZrUTNsTE84b3J2RTdXUEU1TzEyWkEuUTgxNXQQtIwI"
    vault_namespace="admin"
    duration = "10s"
    report_mode = "terse"
    random_mounts = true
    cleanup = true

    test "kube_auth" "kube_auth_test1" {
      weight = 100
      config {
        auth {
          kubernetes_host = "https://kubernetes.default.svc"
        }
        role {
          name = "vault-benchmark-role"
          bound_service_account_names = ["vault-benchmark"]
          bound_service_account_namespaces = ["*"]
          token_max_ttl = "24h"
          token_ttl = "30m"
        }
      }
    }

---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-benchmark
  namespace: vault-ns
spec:
  backoffLimit: 0
  template:
    metadata:
      name: vault-benchmark
      labels:
        app: vault-benchmark
    spec:
      containers:
      - name: vault-benchmark
        image: hashicorp/vault-benchmark:latest
        imagePullPolicy: IfNotPresent
        command: ["vault-benchmark"]
        args: [
          "run",
          "-config=/config/k8s.hcl",
        ]
        volumeMounts:
        - name: benchmark-config
          mountPath: "/config"
          readOnly: true
      restartPolicy: Never
      serviceAccountName: vault-benchmark
      volumes:
      - name: benchmark-config
        configMap:
          name: vault-benchmark-configmap
